### ISSUE TITLE
thread 'main' panicked at src/main.rs:81:49

### ISSUE THREAD

**Issue by KDBalashevich** [chmouel/raffi#52]
When I try to run the binary I get:

**./raffi**

> thread 'main' panicked at src/main.rs:81:49:
> cannot open config file /home/balkd/.config/raffi/raffi.yaml
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**RUST_BACKTRACE=1 ./raffi**

> thread 'main' panicked at src/main.rs:81:49:
> cannot open config file /home/balkd/.config/raffi/raffi.yaml
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
>    1: core::panicking::panic_fmt
>              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
>    2: raffi::read_config::{{closure}}
>    3: raffi::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**RUST_BACKTRACE=full ./raffi**

> thread 'main' panicked at src/main.rs:81:49:
> cannot open config file /home/balkd/.config/raffi/raffi.yaml
> stack backtrace:
>    0:     0x5556b359d60c - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
>    1:     0x5556b359d60c - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
>    2:     0x5556b359d60c - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
>    3:     0x5556b359d60c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
>    4:     0x5556b35c6e0c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
>    5:     0x5556b35c6e0c - core::fmt::write::ha37c23b175e921b3
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
>    6:     0x5556b359a88e - std::io::Write::write_fmt::haa1b000741bcbbe1
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
>    7:     0x5556b359d3f4 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
>    8:     0x5556b359d3f4 - std::sys_common::backtrace::print::hb982056c6f29541c
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
>    9:     0x5556b359e973 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
>   10:     0x5556b359e694 - std::panicking::default_hook::hb8810fe276772c66
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
>   11:     0x5556b359eef5 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
>   12:     0x5556b359edf1 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
>   13:     0x5556b359db36 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
>   14:     0x5556b359eb42 - rust_begin_unwind
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
>   15:     0x5556b3540e45 - core::panicking::panic_fmt::h979245e2fdb2fabd
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
>   16:     0x5556b354380e - raffi::read_config::{{closure}}::h36cb462f390be405
>   17:     0x5556b354790b - raffi::main::hb1c34b835e78544e
>   18:     0x5556b35548d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf15df90d9d97935c
>   19:     0x5556b3558439 - std::rt::lang_start::{{closure}}::h6942ec1f28e7be3d
>   20:     0x5556b359674b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb252e2
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
>   21:     0x5556b359674b - std::panicking::try::do_call::h629e203a624883e4
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
>   22:     0x5556b359674b - std::panicking::try::h7b61614724d6a4f1
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
>   23:     0x5556b359674b - std::panic::catch_unwind::h354ac1c0268491d8
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
>   24:     0x5556b359674b - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
>   25:     0x5556b359674b - std::panicking::try::do_call::h54583f67455bff32
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
>   26:     0x5556b359674b - std::panicking::try::hb0e12c4e01d39dc2
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
>   27:     0x5556b359674b - std::panic::catch_unwind::h367b6339e3ca9a3b
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
>   28:     0x5556b359674b - std::rt::lang_start_internal::ha5ce8533eaa0fda8
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
>   29:     0x5556b3548d45 - main
>   30:     0x7fa2c1a23b4c - __libc_start_call_main
>                                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
>   31:     0x7fa2c1a23c05 - __libc_start_main_impl
>                                at ./csu/../csu/libc-start.c:360:3
>   32:     0x5556b35415a5 - _start
>   33:                0x0 - <unknown>

**Comment by chmouel** [comment]
ah thanks, i'll fix the backtrace,  but you just need a raffi.yaml to get started

**Comment by KDBalashevich** [comment]
> ah thanks, i'll fix the backtrace, but you just need a raffi.yaml to get started

Thank you, I tried creating raffi.yaml, but it does not help:

**./raffi**
> thread 'main' panicked at src/main.rs:165:77:
> called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**RUST_BACKTRACE=1 ./raffi**
> thread 'main' panicked at src/main.rs:165:77:
> called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
>    1: core::panicking::panic_fmt
>              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
>    2: core::result::unwrap_failed
>              at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
>    3: raffi::save_to_cache_file
>    4: raffi::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**RUST_BACKTRACE=full ./raffi**
> thread 'main' panicked at src/main.rs:165:77:
> called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> stack backtrace:
>    0:     0x55c99553f60c - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
>    1:     0x55c99553f60c - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
>    2:     0x55c99553f60c - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
>    3:     0x55c99553f60c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
>    4:     0x55c995568e0c - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
>    5:     0x55c995568e0c - core::fmt::write::ha37c23b175e921b3
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
>    6:     0x55c99553c88e - std::io::Write::write_fmt::haa1b000741bcbbe1
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
>    7:     0x55c99553f3f4 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
>    8:     0x55c99553f3f4 - std::sys_common::backtrace::print::hb982056c6f29541c
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
>    9:     0x55c995540973 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
>   10:     0x55c995540694 - std::panicking::default_hook::hb8810fe276772c66
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
>   11:     0x55c995540ef5 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
>   12:     0x55c995540df1 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
>   13:     0x55c99553fb36 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
>   14:     0x55c995540b42 - rust_begin_unwind
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
>   15:     0x55c9954e2e45 - core::panicking::panic_fmt::h979245e2fdb2fabd
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
>   16:     0x55c9954e32e3 - core::result::unwrap_failed::h8c4b86241881fbbb
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
>   17:     0x55c9954e5fea - raffi::save_to_cache_file::h83a95522c6a0061c
>   18:     0x55c9954e7931 - raffi::main::hb1c34b835e78544e
>   19:     0x55c9954f68d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf15df90d9d97935c
>   20:     0x55c9954fa439 - std::rt::lang_start::{{closure}}::h6942ec1f28e7be3d
>   21:     0x55c99553874b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb252e2
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
>   22:     0x55c99553874b - std::panicking::try::do_call::h629e203a624883e4
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
>   23:     0x55c99553874b - std::panicking::try::h7b61614724d6a4f1
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
>   24:     0x55c99553874b - std::panic::catch_unwind::h354ac1c0268491d8
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
>   25:     0x55c99553874b - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
>   26:     0x55c99553874b - std::panicking::try::do_call::h54583f67455bff32
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
>   27:     0x55c99553874b - std::panicking::try::hb0e12c4e01d39dc2
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
>   28:     0x55c99553874b - std::panic::catch_unwind::h367b6339e3ca9a3b
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
>   29:     0x55c99553874b - std::rt::lang_start_internal::ha5ce8533eaa0fda8
>                                at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
>   30:     0x55c9954ead45 - main
>   31:     0x7f16b5a23b4c - __libc_start_call_main
>                                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
>   32:     0x7f16b5a23c05 - __libc_start_main_impl
>                                at ./csu/../csu/libc-start.c:360:3
>   33:     0x55c9954e35a5 - _start
>   34:                0x0 - <unknown>

**Comment by chmouel** [comment]
humm interesting, i have moved to use a new library for error handling, let me know if this works better for you:

should print something like this now when there is an error (error when the config file is not there)


```bash
% cargo run -q
Error: cannot open config file /home/chmouel/.config/raffi/raffi.yaml

Caused by:
    No such file or directory (os error 2)
    ```

**Comment by KDBalashevich** [comment]
> humm interesting, i have moved to use a new library for error handling, let me know if this works better for you:
> 

When there is no raffi.yaml:
```
Error: cannot open config file /home/balkd/.config/raffi/raffi.yaml

Caused by:
    No such file or directory (os error 2)
```

When there is raffi.yaml:
**raffi**
```
thread 'main' panicked at /home/balkd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/raffi-0.4.0/src/main.rs:169:77:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**RUST_BACKTRACE=1 raffi**
```
thread 'main' panicked at /home/balkd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/raffi-0.4.0/src/main.rs:169:77:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: raffi::save_to_cache_file
   4: raffi::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
**RUST_BACKTRACE=full raffi**
```
thread 'main' panicked at /home/balkd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/raffi-0.4.0/src/main.rs:169:77:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x56026a877a9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc3b88a0ed6c5afbf
   1:     0x56026a8a109b - core::fmt::write::hf0030323ef2de926
   2:     0x56026a874ace - std::io::Write::write_fmt::h69911cb4c8790a1f
   3:     0x56026a877885 - std::sys_common::backtrace::print::he441f447f0231532
   4:     0x56026a878df4 - std::panicking::default_hook::{{closure}}::hbd5dbffb1b120121
   5:     0x56026a878b13 - std::panicking::default_hook::h35452db54148727c
   6:     0x56026a87939f - std::panicking::rust_panic_with_hook::h37faa341ad29f7fd
   7:     0x56026a879291 - std::panicking::begin_panic_handler::{{closure}}::h02e511cdf7bc65a2
   8:     0x56026a877fc6 - std::sys_common::backtrace::__rust_end_short_backtrace::h978128bcc3d8fca0
   9:     0x56026a878fb2 - rust_begin_unwind
  10:     0x56026a81a345 - core::panicking::panic_fmt::hef80f46d93299868
  11:     0x56026a81a7e3 - core::result::unwrap_failed::hab2c6de8243ff0ae
  12:     0x56026a81d368 - raffi::save_to_cache_file::h920ddaa49718ed02
  13:     0x56026a81efd2 - raffi::main::h3e19d0bc309b3f85
  14:     0x56026a82d513 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9d2386e70f134d65
  15:     0x56026a83175d - std::rt::lang_start::{{closure}}::h71523b94ffad891b
  16:     0x56026a86fed8 - std::rt::lang_start_internal::h96d2d059d51f9fde
  17:     0x56026a821d05 - main
  18:     0x7f83df823b4c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19:     0x7f83df823c05 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  20:     0x56026a81aae1 - _start
                               at /builddir/glibc-2.38/csu/../sysdeps/x86_64/start.S:115
  21:                0x0 - <unknown>
```

**Comment by feathecutie** [comment]
I just ran into the same error, I believe the problem is that raffi does not actually create it's cache directory, but tries to use it.
After creating the directory `~/.cache/raffi/` manually, raffi worked perfectly.

**Comment by chmouel** [comment]
I believe i have fixed this some time ago in this commit: https://github.com/chmouel/raffi/commit/fa2d456e05a5bce17c888a8c553ef08eec00fdee
